name: WebDriverIO TypeScript BDD CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run smoke

  regression:
    needs: [smoke]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run regression

    - name: Generate Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: CucumberHTMLReport
        path: reports/html
